-- Hacking Hub Admin Dashboard - Member Persistence Migration
-- Run this in the Supabase SQL Editor (after schema.sql has already been applied).
--
-- Part 1 fixes a live bug: every "admin full write access" policy in schema.sql
-- checks admin status via a subquery on public.profiles from *within a policy on
-- profiles itself*, which Postgres rejects with "infinite recursion detected in
-- policy for relation profiles" (42P17). This means no admin write has ever
-- actually succeeded against this project. The fix is a SECURITY DEFINER helper
-- function, which runs with elevated privileges and bypasses RLS internally,
-- breaking the recursion cycle.
--
-- Part 2 adds tables for data that doesn't fit the existing auth.users-keyed
-- schema: real members here are PayFast payers identified by email, not people who
-- have signed into this app via Google OAuth, so these are keyed by email instead
-- of a foreign key to auth.users.

-- =========================================================================
-- PART 1: FIX THE RLS RECURSION BUG
-- =========================================================================

CREATE OR REPLACE FUNCTION public.is_admin(uid UUID)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles WHERE profiles.id = uid AND profiles.role = 'admin'
  );
$$;

DROP POLICY IF EXISTS "Allow admins full write access to profiles" ON public.profiles;
CREATE POLICY "Allow admins full write access to profiles" ON public.profiles
    FOR ALL USING (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS "Allow admins full write access to meetups" ON public.meetups;
CREATE POLICY "Allow admins full write access to meetups" ON public.meetups
    FOR ALL USING (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS "Allow admins full write access to 1on1 sessions" ON public.one_on_ones;
CREATE POLICY "Allow admins full write access to 1on1 sessions" ON public.one_on_ones
    FOR ALL USING (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS "Allow admins full write access to certifications" ON public.certifications;
CREATE POLICY "Allow admins full write access to certifications" ON public.certifications
    FOR ALL USING (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS "Allow admins full write access to payments" ON public.payments;
CREATE POLICY "Allow admins full write access to payments" ON public.payments
    FOR ALL USING (public.is_admin(auth.uid()));

-- =========================================================================
-- PART 2: MEMBER PERSISTENCE TABLES (keyed by email, admin-only)
-- =========================================================================

-- Editable profile fields with no source in the PayFast export.
CREATE TABLE IF NOT EXISTS public.member_profiles (
    email TEXT PRIMARY KEY,
    age TEXT,
    gender TEXT,
    location TEXT,
    specialty TEXT,
    linkedin TEXT,
    phone TEXT,
    money_owed NUMERIC NOT NULL DEFAULT 0,
    job_readiness TEXT,
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Active (Permanent)', 'Left')),
    employment_status TEXT,
    job_title TEXT,
    monthly_remuneration NUMERIC NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.member_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage member_profiles" ON public.member_profiles;
CREATE POLICY "Admins manage member_profiles" ON public.member_profiles
    FOR ALL USING (public.is_admin(auth.uid()));

-- Members added by hand, with no PayFast payment yet.
CREATE TABLE IF NOT EXISTS public.manual_members (
    email TEXT PRIMARY KEY,
    member TEXT NOT NULL,
    start_date DATE NOT NULL,
    last_plan TEXT NOT NULL,
    total_spent NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.manual_members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage manual_members" ON public.manual_members;
CREATE POLICY "Admins manage manual_members" ON public.manual_members
    FOR ALL USING (public.is_admin(auth.uid()));

-- Manually recorded EFT payments (business bank account, not PayFast).
CREATE TABLE IF NOT EXISTS public.eft_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pf_id TEXT NOT NULL,
    member TEXT NOT NULL,
    email TEXT NOT NULL,
    plan TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    fee NUMERIC NOT NULL DEFAULT 0,
    net NUMERIC NOT NULL,
    funding_type TEXT NOT NULL DEFAULT 'EFT',
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL DEFAULT 'COMPLETE',
    bank_reference TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.eft_payments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage eft_payments" ON public.eft_payments;
CREATE POLICY "Admins manage eft_payments" ON public.eft_payments
    FOR ALL USING (public.is_admin(auth.uid()));
