-- Hacking Hub Admin Dashboard - Member Reviews / Feedback
-- Run this in the Supabase SQL Editor after 002_member_persistence.sql,
-- 003_job_placed_date.sql, and 004_member_access_control.sql have already been applied.
--
-- Members can leave reviews, criticism, recommendations, and general feedback, and
-- choose per-review whether it's shared with the community or private to admins only.

CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    member_name TEXT NOT NULL,
    rating INT CHECK (rating BETWEEN 1 AND 5),
    category TEXT NOT NULL DEFAULT 'General'
        CHECK (category IN ('Praise', 'Criticism', 'Recommendation', 'Feature Request', 'General')),
    title TEXT,
    body TEXT NOT NULL,
    visibility TEXT NOT NULL DEFAULT 'Private' CHECK (visibility IN ('Public', 'Private')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Admins see and manage everything, same pattern as every other admin table so far.
DROP POLICY IF EXISTS "Admins manage reviews" ON public.reviews;
CREATE POLICY "Admins manage reviews" ON public.reviews
    FOR ALL USING (public.is_admin(auth.uid()));

-- A member can only insert a review under their own verified sign-in email, never
-- someone else's - enforced server-side, not just trusted from the client.
DROP POLICY IF EXISTS "Members insert own reviews" ON public.reviews;
CREATE POLICY "Members insert own reviews" ON public.reviews
    FOR INSERT WITH CHECK (auth.jwt() ->> 'email' = email);

-- A member sees Public reviews from anyone, plus their own regardless of visibility -
-- never another member's private submission.
DROP POLICY IF EXISTS "Members view public and own reviews" ON public.reviews;
CREATE POLICY "Members view public and own reviews" ON public.reviews
    FOR SELECT USING (visibility = 'Public' OR auth.jwt() ->> 'email' = email);
