-- Hacking Hub Admin Dashboard - Restrict Access to Community Contacts
--
-- HISTORICAL RECORD ONLY - REDACTED. This migration ran once to narrow
-- real portal access to the community contact list at the time (granting
-- access to that list, and explicitly revoking it from ~33 real members
-- who were not on it - the revoke list is arguably more sensitive than
-- membership alone). It originally contained the real email/name lists
-- for both the grant and the revoke, which a later PII review found still
-- committed and publicly fetchable in this public repo.
--
-- The real lists now live only in
-- supabase/.private-history/021_sync_community_allowlist.full.sql
-- (gitignored, local-only) - this migration already ran against the live
-- database (the `member_profiles.status` values it set are still live
-- today), so there is nothing left to re-run. This file has zero reusable
-- schema of its own (confirmed - it was 100% one-time data), so it's kept
-- only as a placeholder in the migration sequence for continuity with
-- other files' "run after 002-019" ordering comments, not meant to be
-- executed again.
