-- Hacking Hub Admin Dashboard - Member Roadmaps (batch import)
-- Run this in the Supabase SQL Editor after 028_roadmap.sql has been applied.
-- Safe to re-run: see the idempotency note below - it's a bit different from
-- most migrations in this project because of the standard-catalog retrofit.
--
-- One running file for roadmaps handed over as real, individually-written
-- coaching docs (Google Docs, pasted in one at a time) - NOT a new migration
-- per person going forward. Every future member's roadmap should be entered
-- directly through the Roadmaps admin tab (it's built for exactly this);
-- this file exists only to bulk-seed the ones that already existed as docs
-- before that tab did, appending one block per member as each doc comes in.
--
-- Every assigned roadmap's Core Foundations phase now draws its
-- Certifications from one standard 8-item catalog (CORE_FOUNDATIONS_CATALOG
-- in src/lib/memberOptions.js) - a member needs at least 4 of the 8 done.
-- Whatever a member's doc originally listed under Core Foundations
-- Certifications that ISN'T one of these 8 (e.g. a THM room-count goal, a
-- second SOC/CySA+ cert) has been dropped from Certifications - real
-- progress on the 8 that do match is preserved. This was a deliberate,
-- explicitly confirmed retrofit, not an oversight: existing per-member
-- variation gave way to one consistent baseline. Networking/Other/
-- Specialization items are untouched.
--
-- Idempotency: each person's Core Foundations Certifications rows are
-- unconditionally replaced (DELETE then INSERT) every time this file runs,
-- so re-running it re-applies the standard catalog even if an earlier
-- version of this file already ran. Their Networking/Other/Specialization
-- rows are only inserted the first time (guarded on whether any row OTHER
-- than Core Foundations Certifications already exists for that member), so
-- =========================================================================
-- REAL PER-MEMBER DATA - REDACTED. Below this point, this file originally
-- held one block per real member (name in a comment, real email, and
-- granular per-cert coaching progress notes) for ~30 members whose
-- roadmaps existed as individually-written coaching docs before the
-- Roadmaps admin tab did. A later PII review found it still committed and
-- publicly fetchable in this public repo. The real content now lives only
-- in supabase/.private-history/029_member_roadmaps.full.sql (gitignored,
-- local-only) - it already ran against the live database, so there is
-- nothing to re-run here. This file has zero reusable schema of its own
-- (the header above already says so - every future member's roadmap goes
-- through the Roadmaps admin tab, not a new migration), so it's kept only
-- as a placeholder in the migration sequence for continuity.
-- =========================================================================
