-- Hacking Hub Admin Dashboard - AI Interview Prep
-- Run this in the Supabase SQL Editor after 002-055 have already been
-- applied. Safe to re-run: every statement is idempotent.
--
-- The "More 1on1 Support" area on the Meetings tab has always had a
-- "Request Interview Prep" card - a mailto: link asking Siya to run a
-- mock interview by hand. This adds an instant AI alternative alongside
-- it (not replacing it - a human session is still worth keeping as an
-- option): paste a job description + CV text, get back tailored
-- interview questions generated by Gemma.
--
-- Unlike cv_reviews (055_cv_reviews.sql), the job description IS stored
-- here - it's a public job posting, not personal data, and keeping it
-- gives useful context if a member revisits this session later. The CV
-- text itself still isn't stored, same reasoning as cv_reviews.

CREATE TABLE IF NOT EXISTS public.interview_prep_sessions (
  id BIGSERIAL PRIMARY KEY,
  member_email TEXT NOT NULL,
  job_description TEXT NOT NULL,
  -- [{"question": "...", "category": "Technical", "tip": "..."}, ...]
  questions JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_interview_prep_member_created ON public.interview_prep_sessions(member_email, created_at);

ALTER TABLE public.interview_prep_sessions ENABLE ROW LEVEL SECURITY;

-- Self-owned, same shape as cv_reviews - no client-facing INSERT policy,
-- only the gemma-interview-prep Edge Function writes here via the
-- service-role key.
DROP POLICY IF EXISTS "members read own interview prep sessions" ON public.interview_prep_sessions;
CREATE POLICY "members read own interview prep sessions"
  ON public.interview_prep_sessions FOR SELECT
  USING (member_email = lower(auth.jwt() ->> 'email'));

DROP POLICY IF EXISTS "admins manage interview prep sessions" ON public.interview_prep_sessions;
CREATE POLICY "admins manage interview prep sessions"
  ON public.interview_prep_sessions FOR ALL
  USING (public.is_admin(auth.uid()));
