-- Hacking Hub Admin Dashboard Database Schema
-- Run this in the Supabase SQL Editor to initialize the database tables, triggers, and Row-Level Security (RLS) policies.

-- 1. Create Profiles Table (Role-based user management)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    avatar_url TEXT,
    role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 2. Create Meetups Table
CREATE TABLE public.meetups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    location TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'completed', 'cancelled')),
    rsvps INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on Meetups
ALTER TABLE public.meetups ENABLE ROW LEVEL SECURITY;

-- 3. Create 1on1 Sessions Table
CREATE TABLE public.one_on_ones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    mentor_name TEXT NOT NULL,
    time TIMESTAMP WITH TIME ZONE NOT NULL,
    topic TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled')),
    roadmap_progress INT DEFAULT 0 CHECK (roadmap_progress BETWEEN 0 AND 100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on 1on1s
ALTER TABLE public.one_on_ones ENABLE ROW LEVEL SECURITY;

-- 4. Create Certifications Table
CREATE TABLE public.certifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    cohort TEXT NOT NULL,
    date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on Certifications
ALTER TABLE public.certifications ENABLE ROW LEVEL SECURITY;

-- 5. Create Payments Table
CREATE TABLE public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    plan TEXT NOT NULL,
    amount TEXT NOT NULL, -- e.g. "R 650.00"
    date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'unpaid' CHECK (status IN ('paid', 'unpaid')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on Payments
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;


-- =========================================================================
-- SECURITY POLICIES (Row-Level Security)
-- =========================================================================

-- Profiles Policies
CREATE POLICY "Allow public read-access to profile metadata" ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Allow users to update their own profiles" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Allow admins full write access to profiles" ON public.profiles
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE public.profiles.id = auth.uid() AND public.profiles.role = 'admin'
        )
    );

-- Meetups Policies
CREATE POLICY "Allow anyone to read meetups" ON public.meetups
    FOR SELECT USING (true);

CREATE POLICY "Allow admins full write access to meetups" ON public.meetups
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE public.profiles.id = auth.uid() AND public.profiles.role = 'admin'
        )
    );

-- 1on1 Sessions Policies
CREATE POLICY "Allow members to view their own sessions" ON public.one_on_ones
    FOR SELECT USING (auth.uid() = member_id);

CREATE POLICY "Allow admins full write access to 1on1 sessions" ON public.one_on_ones
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE public.profiles.id = auth.uid() AND public.profiles.role = 'admin'
        )
    );

-- Certifications Policies
CREATE POLICY "Allow anyone to view certification deadlines" ON public.certifications
    FOR SELECT USING (true);

CREATE POLICY "Allow admins full write access to certifications" ON public.certifications
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE public.profiles.id = auth.uid() AND public.profiles.role = 'admin'
        )
    );

-- Payments Policies
CREATE POLICY "Allow members to view their own payment ledger" ON public.payments
    FOR SELECT USING (auth.uid() = member_id);

CREATE POLICY "Allow admins full write access to payments" ON public.payments
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE public.profiles.id = auth.uid() AND public.profiles.role = 'admin'
        )
    );


-- =========================================================================
-- AUTOMATED PROFILE CREATION TRIGGER
-- =========================================================================

-- Create trigger function to create profile entry when a user signs up/logs in via Google OAuth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name, avatar_url, role)
    VALUES (
        new.id,
        new.email,
        new.raw_user_meta_data->>'full_name',
        new.raw_user_meta_data->>'avatar_url',
        CASE 
            WHEN new.email LIKE '%@hackinghub.co.za' THEN 'admin'
            ELSE 'member'
        END
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger execution bind
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
